name: Publish to Winget
on:
  workflow_dispatch:
    inputs:
      manual:
        description: Manual run (bypass default conditions)
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          echo "${{ github.sha }} Current time: $(date '+%Y-%m-%d %H:%M:%S')" > Release.txt
      - name: Test
        run: cat Release.txt
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          name: latest
          prerelease: true
          files: |
            Release.txt